# Configure Platform Name

EDXAPP_PLATFORM_NAME: "Branch Academy"

# Configure DNS for site and email links
# Must be the same with LMS and CMS URL from  
EDXAPP_LMS_BASE: 'branchacademy.cloudswyft.com'
EDXAPP_CMS_BASE: 'studio-branchacademy.cloudswyft.com'
EDXAPP_SITE_NAME: '{{ EDXAPP_LMS_BASE }}'
EDXAPP_LMS_SITE_NAME: '{{ EDXAPP_LMS_BASE }}'
EDXAPP_CMS_SITE_NAME: '{{ EDXAPP_CMS_BASE }}'

# FROM Eamils
EDXAPP_TECH_SUPPORT_EMAIL: 'support@cloudswyft.com'
EDXAPP_CONTACT_EMAIL: 'support@cloudswyft.com'
EDXAPP_BUGS_EMAIL: 'support@cloudswyft.com'
EDXAPP_DEFAULT_FROM_EMAIL: 'support@cloudswyft.com'
EDXAPP_DEFAULT_FEEDBACK_EMAIL: 'support@cloudswyft.com'
EDXAPP_DEFAULT_SERVER_EMAIL: 'support@cloudswyft.com'
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: 'support@cloudswyft.com'
EDXAPP_UNIVERSITY_EMAIL: 'support@cloudswyft.com'
EDXAPP_PRESS_EMAIL: 'support@cloudswyft.com'
EDXAPP_PAYMENT_SUPPORT_EMAIL: "support@cloudswyft.com"
